sudo: required

services:
  - docker

before_install:
  - docker build -t yairelmaliah/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yairelmaliah/react-test npm test

after_success:
  - docker build -t yairelmaliah/multi-client ./client
  - docker build -t yairelmaliah/multi-nginx ./nginx
  - docker build -t yairelmaliah/multi-server ./server
  - docker build -t yairelmaliah/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push all images to docker hub
  - docker push yairelmaliah/multi-client
  - docker push yairelmaliah/multi-nginx
  - docker push yairelmaliah/multi-server
  - docker push yairelmaliah/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-952277248628
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY